import { useState } from 'react'
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'

const login = () => {

    const navigate = useRouter()

    const [credentials, setCredentials] = useState({
        email: '',
        password: ''
    })

    const handleChange = (e) => {
        setCredentials({
            ...credentials,
            [e.target.name]: e.target.value
        })
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        try {
            const res = await axios.post('/api/auth/login', credentials)
            console.log(res)
        }
        catch (err) {
            console.log(err)
        }
        finally {
            navigate.push('/')
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>holap</h1>
                <form action="" onSubmit={handleSubmit}>
                    <input type="text" name='email' placeholder='email...' onChange={handleChange} />
                    <input type="text" placeholder='password...' name='password' onChange={handleChange} />
                    <button>Login...</button>
                </form>
            </main>
        </>
    )
}

export default login