import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children, title }) => {
    return (
        <>
            <Head>
                <title>MyRoad | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-[#171717] min-h-screen">
                <Navbar />
                {children}
            </main>
        </>

    )
}

export default Layout